[package]
name = "renderer"
version = "0.0.1"
authors = ["Huon Wilson <dbau.pp@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
glob = "^0.2"
