#!/bin/sh

git clone https://github.com/rfdonnelly/crate-galaxy-data.git
./add-data
cd crate-galaxy-data
git add .
git config user.name "Travis CI"
git config user.email "travis@travis-ci.org"
git commit -m "Build $TRAVIS_BUILD_NUMBER"
git push https://$GITHUB_TOKEN@github.com/rfdonnelly/crate-galaxy-data.git master >/dev/null 2>&1
